export type FirebaseCollectionName =
  | "siteSettings"
  | "menuItems"
  | "menuCategories"
  | "branches"
  | "pressItems"
  | "brandStories"
  | "galleryImages"
  | "contactMessages"
  | "careerApplications"
  | "customerClubSignups"
  | "emailCampaigns"
  | "orderLinks"
  | "siteImageOverrides"
  | "homepageMenuShowcase"
  | "announcementPopup"
  | "seoContent"
  | "adminUsers";
